SCREENER_PARAMS = {
        "annual_pnl_recent": {
            "Sales": "Annual sales/revenue",
            "OPM": "Operating Profit Margin",
            "Profit after tax": "Net profit after tax",
            "Return on capital employed": "ROCE percentage",
            "EPS": "Earnings Per Share",
            "Change in promoter holding": "Change in promoter shareholding",
            "Sales last year": "Previous year sales",
            "Operating profit last year": "Previous year operating profit",
            "Other income last year": "Previous year other income",
            "EBIDT last year": "Previous year EBIDT",
            "Depreciation last year": "Previous year depreciation",
            "EBIT last year": "Previous year EBIT",
            "Interest last year": "Previous year interest expenses",
            "Profit before tax last year": "Previous year PBT",
            "Tax last year": "Previous year tax",
            "Profit after tax last year": "Previous year PAT",
            "Extraordinary items last year": "Previous year extraordinary items",
            "Net Profit last year": "Previous year net profit",
            "Dividend last year": "Previous year dividend",
            "Material cost last year": "Previous year material cost",
            "Employee cost last year": "Previous year employee cost",
            "OPM last year": "Previous year operating profit margin",
            "NPM last year": "Previous year net profit margin",
            "Operating profit": "Current operating profit",
            "Interest": "Current interest expenses",
            "Depreciation": "Current depreciation",
            "EPS last year": "Previous year EPS",
            "EBIT": "Earnings Before Interest and Tax",
            "Net profit": "Current net profit",
            "Current Tax": "Current tax expenses",
            "Tax": "Total tax",
            "Other income": "Other income",
            "Last annual result date": "Date of last annual results"
        },
        "annual_pnl_preceding": {
            "Sales preceding year": "Sales from year before last",
            "Operating profit preceding year": "Operating profit from year before last",
            "Other income preceding year": "Other income from year before last",
            "EBIDT preceding year": "EBIDT from year before last",
            "Depreciation preceding year": "Depreciation from year before last",
            "EBIT preceding year": "EBIT from year before last",
            "Interest preceding year": "Interest from year before last",
            "Profit before tax preceding year": "PBT from year before last",
            "Tax preceding year": "Tax from year before last",
            "Profit after tax preceding year": "PAT from year before last",
            "Extraordinary items preceding year": "Extraordinary items from year before last",
            "Net Profit preceding year": "Net profit from year before last",
            "Dividend preceding year": "Dividend from year before last",
            "OPM preceding year": "OPM from year before last",
            "NPM preceding year": "NPM from year before last",
            "EPS preceding year": "EPS from year before last",
            "Sales preceding 12months": "Sales from preceding 12 months",
            "Net profit preceding 12months": "Net profit from preceding 12 months"
        },
        "annual_pnl_historical": {
            "Sales growth 3Years": "3-year sales growth percentage",
            "Sales growth 5Years": "5-year sales growth percentage",
            "Profit growth 3Years": "3-year profit growth percentage",
            "Profit growth 5Years": "5-year profit growth percentage",
            "Sales growth 10years median": "10-year median sales growth",
            "Sales growth 5years median": "5-year median sales growth",
            "Sales growth 7Years": "7-year sales growth percentage",
            "Sales growth 10Years": "10-year sales growth percentage",
            "EBIDT growth 3Years": "3-year EBIDT growth percentage",
            "EBIDT growth 5Years": "5-year EBIDT growth percentage",
            "EBIDT growth 7Years": "7-year EBIDT growth percentage",
            "EBIDT growth 10Years": "10-year EBIDT growth percentage",
            "EPS growth 3Years": "3-year EPS growth percentage",
            "EPS growth 5Years": "5-year EPS growth percentage",
            "EPS growth 7Years": "7-year EPS growth percentage",
            "EPS growth 10Years": "10-year EPS growth percentage",
            "Profit growth 7Years": "7-year profit growth percentage",
            "Profit growth 10Years": "10-year profit growth percentage",
            "Change in promoter holding 3Years": "3-year change in promoter holding",
            "Average Earnings 5Year": "5-year average earnings",
            "Average Earnings 10Year": "10-year average earnings",
            "Average EBIT 5Year": "5-year average EBIT",
            "Average EBIT 10Year": "10-year average EBIT"
        },
        "quarterly_pnl_recent": {
            "Sales latest quarter": "Latest quarter sales",
            "Profit after tax latest quarter": "Latest quarter PAT",
            "YOY Quarterly sales growth": "Year-over-year quarterly sales growth",
            "YOY Quarterly profit growth": "Year-over-year quarterly profit growth",
            "Sales growth": "Quarter-over-quarter sales growth",
            "Profit growth": "Quarter-over-quarter profit growth",
            "Operating profit latest quarter": "Latest quarter operating profit",
            "Other income latest quarter": "Latest quarter other income",
            "EBIDT latest quarter": "Latest quarter EBIDT",
            "Depreciation latest quarter": "Latest quarter depreciation",
            "EBIT latest quarter": "Latest quarter EBIT",
            "Interest latest quarter": "Latest quarter interest",
            "Profit before tax latest quarter": "Latest quarter PBT",
            "Tax latest quarter": "Latest quarter tax",
            "Extraordinary items latest quarter": "Latest quarter extraordinary items",
            "Net Profit latest quarter": "Latest quarter net profit",
            "GPM latest quarter": "Latest quarter gross profit margin",
            "OPM latest quarter": "Latest quarter operating profit margin",
            "NPM latest quarter": "Latest quarter net profit margin",
            "Equity Capital latest quarter": "Latest quarter equity capital",
            "EPS latest quarter": "Latest quarter EPS",
            "Operating profit 2quarters back": "Operating profit 2 quarters ago",
            "Operating profit 3quarters back": "Operating profit 3 quarters ago",
            "Sales 2quarters back": "Sales 2 quarters ago",
            "Sales 3quarters back": "Sales 3 quarters ago",
            "Net profit 2quarters back": "Net profit 2 quarters ago",
            "Net profit 3quarters back": "Net profit 3 quarters ago",
            "Operating profit growth": "Operating profit growth",
            "Last result date": "Date of last quarterly results",
            "Expected quarterly sales growth": "Expected quarterly sales growth",
            "Expected quarterly sales": "Expected quarterly sales",
            "Expected quarterly operating profit": "Expected quarterly operating profit",
            "Expected quarterly net profit": "Expected quarterly net profit",
            "Expected quarterly EPS": "Expected quarterly EPS"
        },
        "quarterly_pnl_preceding": {
            "Sales preceding quarter": "Previous quarter sales",
            "Operating profit preceding quarter": "Previous quarter operating profit",
            "Other income preceding quarter": "Previous quarter other income",
            "EBIDT preceding quarter": "Previous quarter EBIDT",
            "Depreciation preceding quarter": "Previous quarter depreciation",
            "EBIT preceding quarter": "Previous quarter EBIT",
            "Interest preceding quarter": "Previous quarter interest",
            "Profit before tax preceding quarter": "Previous quarter PBT",
            "Tax preceding quarter": "Previous quarter tax",
            "Profit after tax preceding quarter": "Previous quarter PAT",
            "Extraordinary items preceding quarter": "Previous quarter extraordinary items",
            "Net Profit preceding quarter": "Previous quarter net profit",
            "OPM preceding quarter": "Previous quarter OPM",
            "NPM preceding quarter": "Previous quarter NPM",
            "Equity Capital preceding quarter": "Previous quarter equity capital",
            "EPS preceding quarter": "Previous quarter EPS"
        },
        "quarterly_pnl_historical": {
            "Sales preceding year quarter": "Same quarter previous year sales",
            "Operating profit preceding year quarter": "Same quarter previous year operating profit",
            "Other income preceding year quarter": "Same quarter previous year other income",
            "EBIDT preceding year quarter": "Same quarter previous year EBIDT",
            "Depreciation preceding year quarter": "Same quarter previous year depreciation",
            "EBIT preceding year quarter": "Same quarter previous year EBIT",
            "Interest preceding year quarter": "Same quarter previous year interest",
            "Profit before tax preceding year quarter": "Same quarter previous year PBT",
            "Tax preceding year quarter": "Same quarter previous year tax",
            "Profit after tax preceding year quarter": "Same quarter previous year PAT",
            "Extraordinary items preceding year quarter": "Same quarter previous year extraordinary items",
            "Net Profit preceding year quarter": "Same quarter previous year net profit",
            "OPM preceding year quarter": "Same quarter previous year OPM",
            "NPM preceding year quarter": "Same quarter previous year NPM",
            "Equity Capital preceding year quarter": "Same quarter previous year equity capital",
            "EPS preceding year quarter": "Same quarter previous year EPS"
        },
        "balance_sheet_recent": {
            "Debt": "Total debt",
            "Equity capital": "Paid-up equity capital",
            "Preference capital": "Preference share capital",
            "Reserves": "Reserves and surplus",
            "Secured loan": "Secured loans",
            "Unsecured loan": "Unsecured loans",
            "Balance sheet total": "Total balance sheet size",
            "Gross block": "Gross fixed assets",
            "Revaluation reserve": "Asset revaluation reserves",
            "Accumulated depreciation": "Cumulative depreciation",
            "Net block": "Net fixed assets",
            "Capital work in progress": "CWIP",
            "Investments": "Total investments",
            "Current assets": "Current assets",
            "Current liabilities": "Current liabilities",
            "Book value of unquoted investments": "Unquoted investments book value",
            "Market value of quoted investments": "Quoted investments market value",
            "Contingent liabilities": "Contingent liabilities",
            "Total Assets": "Total assets",
            "Working capital": "Working capital (current assets - current liabilities)",
            "Lease liabilities": "Lease liabilities",
            "Inventory": "Inventory/stock",
            "Trade receivables": "Trade receivables/debtors",
            "Face value": "Face value per share",
            "Cash Equivalents": "Cash and cash equivalents",
            "Advance from Customers": "Customer advances",
            "Trade Payables": "Trade payables/creditors"
        },
        "balance_sheet_preceding": {
            "Number of equity shares preceding year": "Equity shares previous year",
            "Debt preceding year": "Debt previous year",
            "Working capital preceding year": "Working capital previous year",
            "Net block preceding year": "Net block previous year",
            "Gross block preceding year": "Gross block previous year",
            "Capital work in progress preceding year": "CWIP previous year"
        },
        "balance_sheet_historical": {
            "Working capital 3Years back": "Working capital 3 years ago",
            "Working capital 5Years back": "Working capital 5 years ago",
            "Working capital 7Years back": "Working capital 7 years ago",
            "Working capital 10Years back": "Working capital 10 years ago",
            "Debt 3Years back": "Debt 3 years ago",
            "Debt 5Years back": "Debt 5 years ago",
            "Debt 7Years back": "Debt 7 years ago",
            "Debt 10Years back": "Debt 10 years ago",
            "Net block 3Years back": "Net block 3 years ago",
            "Net block 5Years back": "Net block 5 years ago",
            "Net block 7Years back": "Net block 7 years ago",
            "Net block 10Years back": "Net block 10 years ago"
        },
        "cashflow_recent": {
            "Cash from operations last year": "Operating cash flow last year",
            "Free cash flow last year": "Free cash flow last year",
            "Cash from investing last year": "Investing cash flow last year",
            "Cash from financing last year": "Financing cash flow last year",
            "Net cash flow last year": "Net cash flow last year",
            "Cash beginning of last year": "Cash at beginning of last year",
            "Cash end of last year": "Cash at end of last year"
        },
        "cashflow_preceding": {
            "Free cash flow preceding year": "Free cash flow preceding year",
            "Cash from operations preceding year": "Operating cash flow preceding year",
            "Cash from investing preceding year": "Investing cash flow preceding year",
            "Cash from financing preceding year": "Financing cash flow preceding year",
            "Net cash flow preceding year": "Net cash flow preceding year",
            "Cash beginning of preceding year": "Cash at beginning of preceding year",
            "Cash end of preceding year": "Cash at end of preceding year"
        },
        "cashflow_historical": {
            "Free cash flow 3years": "3-year free cash flow",
            "Free cash flow 5years": "5-year free cash flow",
            "Free cash flow 7years": "7-year free cash flow",
            "Free cash flow 10years": "10-year free cash flow",
            "Operating cash flow 3years": "3-year operating cash flow",
            "Operating cash flow 5years": "5-year operating cash flow",
            "Operating cash flow 7years": "7-year operating cash flow",
            "Operating cash flow 10years": "10-year operating cash flow",
            "Investing cash flow 10years": "10-year investing cash flow",
            "Investing cash flow 7years": "7-year investing cash flow",
            "Investing cash flow 5years": "5-year investing cash flow",
            "Investing cash flow 3years": "3-year investing cash flow",
            "Cash 3Years back": "Cash 3 years ago",
            "Cash 5Years back": "Cash 5 years ago",
            "Cash 7Years back": "Cash 7 years ago"
        },
        "ratios_recent": {
            "Market Capitalization": "Market cap",
            "Price to Earning": "P/E ratio",
            "Dividend yield": "Dividend yield percentage",
            "Price to book value": "P/B ratio",
            "Return on assets": "ROA percentage",
            "Debt to equity": "Debt-to-equity ratio",
            "Return on equity": "ROE percentage",
            "Promoter holding": "Promoter holding percentage",
            "Earnings yield": "Earnings yield percentage",
            "Pledged percentage": "Promoter pledge percentage",
            "Industry PE": "Industry average P/E",
            "Enterprise Value": "Enterprise value",
            "Number of equity shares": "Number of equity shares",
            "Price to Quarterly Earning": "P/E based on quarterly earnings",
            "Book value": "Book value per share",
            "Inventory turnover ratio": "Inventory turnover ratio",
            "Quick ratio": "Quick ratio",
            "Exports percentage": "Exports as percentage of sales",
            "Piotroski score": "Piotroski financial strength score (0-9)",
            "G Factor": "G Factor score",
            "Asset Turnover Ratio": "Asset turnover ratio",
            "Financial leverage": "Financial leverage ratio",
            "Number of Shareholders": "Total number of shareholders",
            "Unpledged promoter holding": "Unpledged promoter holding percentage",
            "Return on invested capital": "ROIC percentage",
            "Debtor days": "Days sales outstanding",
            "Industry PBV": "Industry average P/B ratio",
            "Credit rating": "Credit rating",
            "Working Capital Days": "Working capital cycle days",
            "Earning Power": "Earning power ratio",
            "Graham Number": "Graham number valuation",
            "Cash Conversion Cycle": "Cash conversion cycle days",
            "Days Payable Outstanding": "Days payable outstanding",
            "Days Receivable Outstanding": "Days receivable outstanding",
            "Days Inventory Outstanding": "Days inventory outstanding",
            "Public holding": "Public holding percentage",
            "FII holding": "FII holding percentage",
            "Change in FII holding": "Change in FII holding",
            "DII holding": "DII holding percentage",
            "Change in DII holding": "Change in DII holding"
        },
        "ratios_preceding": {
            "Book value preceding year": "Book value preceding year",
            "Return on capital employed preceding year": "ROCE preceding year",
            "Return on assets preceding year": "ROA preceding year",
            "Return on equity preceding year": "ROE preceding year",
            "Number of Shareholders preceding quarter": "Shareholders preceding quarter"
        },
        "ratios_historical": {
            "Average return on equity 5Years": "5-year average ROE",
            "Average return on equity 3Years": "3-year average ROE",
            "Number of equity shares 10years back": "Equity shares 10 years ago",
            "Book value 3years back": "Book value 3 years ago",
            "Book value 5years back": "Book value 5 years ago",
            "Book value 10years back": "Book value 10 years ago",
            "Inventory turnover ratio 3Years back": "Inventory turnover 3 years ago",
            "Inventory turnover ratio 5Years back": "Inventory turnover 5 years ago",
            "Inventory turnover ratio 7Years back": "Inventory turnover 7 years ago",
            "Inventory turnover ratio 10Years back": "Inventory turnover 10 years ago",
            "Exports percentage 3Years back": "Exports percentage 3 years ago",
            "Exports percentage 5Years back": "Exports percentage 5 years ago",
            "Average 5years dividend": "5-year average dividend",
            "Average return on capital employed 3Years": "3-year average ROCE",
            "Average return on capital employed 5Years": "5-year average ROCE",
            "Average return on capital employed 7Years": "7-year average ROCE",
            "Average return on capital employed 10Years": "10-year average ROCE",
            "Average return on equity 10Years": "10-year average ROE",
            "Average return on equity 7Years": "7-year average ROE",
            "Return on equity 5years growth": "5-year ROE growth",
            "OPM 5Year": "5-year OPM",
            "OPM 10Year": "10-year OPM",
            "Number of Shareholders 1year back": "Shareholders 1 year ago",
            "Average dividend payout 3years": "3-year average dividend payout",
            "Average debtor days 3years": "3-year average debtor days",
            "Debtor days 3years back": "Debtor days 3 years ago",
            "Debtor days 5years back": "Debtor days 5 years ago",
            "Return on assets 5years": "5-year ROA",
            "Return on assets 3years": "3-year ROA",
            "Historical PE 3Years": "3-year historical P/E",
            "Historical PE 10Years": "10-year historical P/E",
            "Historical PE 7Years": "7-year historical P/E",
            "Historical PE 5Years": "5-year historical P/E",
            "Market Capitalization 3years back": "Market cap 3 years ago",
            "Market Capitalization 5years back": "Market cap 5 years ago",
            "Market Capitalization 7years back": "Market cap 7 years ago",
            "Market Capitalization 10years back": "Market cap 10 years ago",
            "Average Working Capital Days 3years": "3-year average working capital days",
            "Change in FII holding 3Years": "3-year change in FII holding",
            "Change in DII holding 3Years": "3-year change in DII holding"
        },
        "price_recent": {
            "Current price": "Current stock price",
            "Return over 3months": "3-month return percentage",
            "Return over 6months": "6-month return percentage",
            "Is SME": "Is SME stock (boolean)",
            "Is not SME": "Is not SME stock (boolean)",
            "Volume 1month average": "1-month average volume",
            "Volume 1week average": "1-week average volume",
            "Volume": "Current volume",
            "High price": "52-week high price",
            "Low price": "52-week low price",
            "High price all time": "All-time high price",
            "Low price all time": "All-time low price",
            "Return over 1day": "1-day return percentage",
            "Return over 1week": "1-week return percentage",
            "Return over 1month": "1-month return percentage",
            "DMA 50": "50-day moving average",
            "DMA 200": "200-day moving average",
            "DMA 50 previous day": "50-day DMA previous day",
            "DMA 200 previous day": "200-day DMA previous day",
            "RSI": "Relative Strength Index",
            "MACD": "MACD indicator",
            "MACD Previous Day": "MACD previous day",
            "MACD Signal": "MACD signal line",
            "MACD Signal Previous Day": "MACD signal previous day"
        },
        "price_historical": {
            "Return over 1year": "1-year return percentage",
            "Return over 3years": "3-year return percentage",
            "Return over 5years": "5-year return percentage",
            "Volume 1year average": "1-year average volume",
            "Return over 7years": "7-year return percentage"
        }
    }


SCREENER_OPERATORS = {
                "supported_operators": ["+", "-", "/", "*", ">", "<", "AND", "OR"],
                "examples": [
                    "Piotroski score > 7",
                    "Return on equity > 15 AND Debt to equity < 0.5",
                    "Price to Earning < 20 OR Dividend yield > 3",
                    "Sales growth 3Years > 15 AND Profit growth 3Years > 20"
                ]
            }