[project]
name = "sfinance-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "mcp[cli]>=1.9.4",
    "pandas>=2.3.0",
    "sfinance==0.1.3",
]
